# -*- coding: utf-8 -*-
from pathlib import Path

def H(s):
    return "".join(chr(int(x, 16)) for x in s.split())

NL = chr(10)
FOLLOW = H("63a8 7406 7ed3 675f 3002 4ece 73b0 5728 8d77 53ea 8f93 51fa 672c 6ce2 573a 6b21 6b63 6587 548c 3010 672c 6ce2 5feb 7167 3011 3002 7b2c 4e00 884c 5fc5 987b 662f ff1a 7b2c 0025 0073 573a 3002 4e0d 8981 601d 8003 8fc7 7a0b ff0c 4e0d 8981 5206 652f ff0c 4e0d 8981 5927 7eb2 3002")
INNER = H("ff08 5185 90e8 63a8 6f14 5df2 5b8c 6210 ff09")
TRUNC = H("4e0a 4e00 6b21 8f93 51fa 88ab 622a 65ad 3002 4ece 65ad 70b9 540e 7ee7 7eed 5199 ff0c 4e0d 8981 91cd 590d 5df2 5199 6bb5 843d ff0c 4e0d 8981 6539 5199 4e8b 5b9e 3002")
CONT = H("8bf7 63a5 7740 5199 5b8c 672c 6ce2 5269 4f59 573a 6b21 548c 3010 672c 6ce2 5feb 7167 3011 3002")

p = Path(r"D:\视频创作\ace-video-kingdom\tools\world_live_evolve.py")
src = p.read_text(encoding="utf-8")
head = src[:src.find("def _call(")]
main = src[src.find("def main()"):]
print("HAS_FORCE_CALL", "_force_wave(prompt" in main)
print("HAS_ATTEMPTS", "attempts" in main)
if "_force_wave(prompt, next_scene_hint)" not in main:
    raise SystemExit("main_missing_force_call")
if "result.get(" not in main or "attempts" not in main:
    needle = '"scene_headings": scene_hits,'
    idx = main.find(needle)
    if idx < 0:
        raise SystemExit("scene_headings_not_found")
    insert_at = idx + len(needle)
    main = main[:insert_at] + NL + '            "attempts": result.get("attempts") or [],' + main[insert_at:]
    print("REC_INSERTED")
else:
    print("REC_ALREADY")

lines = []
def a(s):
    lines.append(s)

a("def _call(messages: list[dict[str, Any]], max_tokens: int, temperature: float, timeout: float) -> dict[str, Any]:")
a("    data, meta = post_chat_completion(")
a("        base_url=_base_url(),")
a("        api_key=_key(),")
a("        model=MODEL,")
a("        messages=messages,")
a('        asset_store=ROOT / "assets" / "cache" / "transport",')
a("        max_tokens=max_tokens,")
a("        temperature=temperature,")
a("        timeout=timeout,")
a("    )")
a('    choice = (data.get("choices") or [{}])[0]')
a('    message = choice.get("message") or {}')
a('    content = str(message.get("content") or "").strip()')
a('    reasoning = str(message.get("reasoning_content") or "").strip()')
a('    finish = str(choice.get("finish_reason") or "")')
a('    actual = str(data.get("model") or MODEL)')
a('    usage = data.get("usage") or {}')
a("    return {")
a('        "content": content,')
a('        "reasoning": reasoning,')
a('        "finish_reason": finish,')
a('        "actual_model": actual,')
a('        "usage": usage,')
a('        "latency_ms": meta.get("latency_ms"),')
a("    }")
a("")
a("")
a("FOLLOW_BODY = " + repr(FOLLOW))
a("INNER_DONE = " + repr(INNER))
a("TRUNC_HINT = " + repr(TRUNC))
a("CONT_HINT = " + repr(CONT))
a("")
a("")
a("def _force_wave(prompt: str, start_scene: int) -> dict[str, Any]:")
a('    messages: list[dict[str, Any]] = [{"role": "user", "content": prompt}]')
a("    result = _call(messages, max_tokens=8192, temperature=0.88, timeout=180.0)")
a('    text = result["content"]')
a("    attempts = [{")
a('        "kind": "primary",')
a('        "finish_reason": result["finish_reason"],')
a('        "content_len": len(text),')
a('        "reasoning_len": len(result["reasoning"]),')
a('        "usage": result["usage"],')
a('        "latency_ms": result["latency_ms"],')
a("    }]")
a('    print("[world-live] primary finish=%s content=%s reasoning=%s usage=%s" % (')
a('        result["finish_reason"], len(text), len(result["reasoning"]), result["usage"]')
a("    ), flush=True)")
a("    if not text:")
a("        follow = FOLLOW_BODY % start_scene")
a("        messages = [")
a('            {"role": "user", "content": prompt},')
a("            {")
a('                "role": "assistant",')
a('                "content": result["content"] or INNER_DONE,')
a('                "reasoning_content": result["reasoning"],')
a("            },")
a('            {"role": "user", "content": follow},')
a("        ]")
a("        forced = _call(messages, max_tokens=4096, temperature=0.55, timeout=180.0)")
a('        text = forced["content"]')
a("        attempts.append({")
a('            "kind": "force_body",')
a('            "finish_reason": forced["finish_reason"],')
a('            "content_len": len(text),')
a('            "reasoning_len": len(forced["reasoning"]),')
a('            "usage": forced["usage"],')
a('            "latency_ms": forced["latency_ms"],')
a("        })")
a('        print("[world-live] force_body finish=%s content=%s reasoning=%s usage=%s" % (')
a('            forced["finish_reason"], len(text), len(forced["reasoning"]), forced["usage"]')
a("        ), flush=True)")
a("        result = forced")
a('    if text and result["finish_reason"] == "length":')
a('        print("[world-live] truncated, continue", flush=True)')
a("        cont_prompt = CONSTITUTION + chr(10) + TRUNC_HINT + chr(10) + text[-6000:] + chr(10) + CONT_HINT")
a('        cont = _call([{"role": "user", "content": cont_prompt}], max_tokens=2048, temperature=0.7, timeout=180.0)')
a('        text = text.rstrip() + chr(10) + cont["content"]')
a("        attempts.append({")
a('            "kind": "continue",')
a('            "finish_reason": cont["finish_reason"],')
a('            "content_len": len(cont["content"]),')
a('            "reasoning_len": len(cont["reasoning"]),')
a('            "usage": cont["usage"],')
a('            "latency_ms": cont["latency_ms"],')
a("        })")
a("        result = dict(result)")
a('        result["continue"] = attempts[-1]')
a('    if not str(text or "").strip():')
a("        raise RuntimeError(")
a('            "EMPTY_CONTENT finish=%s reasoning_len=%s usage=%s"')
a('            % (result["finish_reason"], len(result.get("reasoning") or ""), result.get("usage"))')
a("        )")
a('    result["content"] = text')
a('    result["attempts"] = attempts')
a("    return result")
a("")
a("")

out = head + NL.join(lines) + main
if not out.endswith(NL):
    out += NL
p.write_text(out, encoding="utf-8")
compile(out, str(p), "exec")
print("REBUILT", p.stat().st_size)
print("HAS_FORCE", "_force_wave" in out)
print("FOLLOW_HEAD", FOLLOW[:8])